### ISSUE TITLE
Error in CoarseNet_train.py

### ISSUE THREAD

**Issue by vijayanand-Git** [luannd/MinutiaeNet#5]
While running the CoarseNet_train.py, I am getting the error "'basestring' is not defined", I tried finding out the solution could not resolve it.

A snippet of the error is attached below:

Learning rate = 0.002
Pretrain dir = ../Models/CoarseNet.h5
Traceback (most recent call last):
  File "CoarseNet_train.py", line 68, in <module>
    logging=logging)
  File "D:\new_pc_work\MinutiaeNet-master\CoarseNet\CoarseNet_model.py", line 255, in train
    img_name, folder_name, img_size = get_maximum_img_size_and_names(train_set, None, max_size=input_shape)
  File "D:\new_pc_work\MinutiaeNet-master\CoarseNet\CoarseNet_utils.py", line 367, in get_maximum_img_size_and_names
    if isinstance(dataset, basestring):
NameError: name 'basestring' is not defined

**Comment by luannd** [comment]
Are you using Python 3?
`basestring` is no longer available in Python 3. So just replace `basestring` with `str`.

**Comment by vijayanand-Git** [comment]
Thanks for the prompt reply, I will change the further error according to python 3.
